use phf::{phf_map, phf_set};

pub fn get_fixed_value(s: &str) -> Option<String> {
    FIXED.get(s).map(|v| match FIXED_INFIX.contains(s) {
        true => format!(" {} ", v),
        false => v.to_string(),
    })
}

pub static FIXED_INFIX: phf::Set<&'static str> = phf_set! {
    "plus",
    "minus",
    "cdot",
    "gtrdot",
    "cdotp",
    "intercal",
    "centerdot",
    "land",
    "rhd",
    "circ",
    "leftthreetimes",
    "rightthreetimes",
    "amalg",
    "circledast",
    "ldotp",
    "rtimes",
    "And",
    "circledcirc",
    "lor",
    "setminus",
    "ast",
    "circleddash",
    "lessdot",
    "smallsetminus",
    "barwedge",
    "Cup",
    "lhd",
    "sqcap",
    "bigcirc",
    "cup",
    "ltimes",
    "sqcup",
    "bmod",
    "curlyvee",
    "mod",
    "times",
    "boxdot",
    "curlywedge",
    "mp",
    "unlhd",
    "boxminus",
    "div",
    "odot",
    "unrhd",
    "boxplus",
    "divideontimes",
    "ominus",
    "uplus",
    "boxtimes",
    "dotplus",
    "oplus",
    "vee",
    "bullet",
    "doublebarwedge",
    "otimes",
    "veebar",
    "Cap",
    "doublecap",
    "oslash",
    "wedge",
    "cap",
    "doublecup",
    "pm",
    "plusmn",
    "wr",
    "nsimeq",
    "congneq",
    "eq",
    "ne",
    "neq",
    "triangleq",
    "doteqdot",
    "lessapprox",
    "smile",
    "eqcirc",
    "lesseqgtr",
    "sqsubset",
    "eqcolon",
    "minuscolon",
    "lesseqqgtr",
    "sqsubseteq",
    "Eqcolon",
    "minuscoloncolon",
    "lessgtr",
    "sqsupset",
    "approx",
    "eqqcolon",
    "equalscolon",
    "lesssim",
    "sqsupseteq",
    "approxcolon",
    "Eqqcolon",
    "equalscoloncolon",
    "ll",
    "Subset",
    "approxcoloncolon",
    "eqsim",
    "lll",
    "subset",
    "sub",
    "approxeq",
    "eqslantgtr",
    "llless",
    "subseteq",
    "sube",
    "asymp",
    "eqslantless",
    "lt",
    "subseteqq",
    "backepsilon",
    "equiv",
    "succ",
    "backsim",
    "fallingdotseq",
    "models",
    "succapprox",
    "backsimeq",
    "frown",
    "multimap",
    "succcurlyeq",
    "between",
    "ge",
    "origof",
    "succeq",
    "bowtie",
    "geq",
    "owns",
    "succsim",
    "bumpeq",
    "geqq",
    "Supset",
    "Bumpeq",
    "geqslant",
    "perp",
    "supset",
    "gg",
    "pitchfork",
    "supseteq",
    "supe",
    "colonapprox",
    "ggg",
    "prec",
    "supseteqq",
    "Colonapprox",
    "coloncolonapprox",
    "gggtr",
    "precapprox",
    "thickapprox",
    "coloneq",
    "colonminus",
    "gt",
    "preccurlyeq",
    "thicksim",
    "Coloneq",
    "coloncolonminus",
    "gtrapprox",
    "preceq",
    "trianglelefteq",
    "coloneqq",
    "colonequals",
    "gtreqless",
    "precsim",
    "Coloneqq",
    "coloncolonequals",
    "gtreqqless",
    "propto",
    "trianglerighteq",
    "colonsim",
    "gtrless",
    "risingdotseq",
    "varpropto",
    "Colonsim",
    "coloncolonsim",
    "gtrsim",
    "shortmid",
    "vartriangle",
    "cong",
    "imageof",
    "shortparallel",
    "vartriangleleft",
    "curlyeqprec",
    "in",
    "isin",
    "sim",
    "vartriangleright",
    "curlyeqsucc",
    "Join",
    "simcolon",
    "vcentcolon",
    "ratio",
    "dashv",
    "le",
    "simcoloncolon",
    "vdash",
    "dblcolon",
    "coloncolon",
    "leq",
    "simeq",
    "vDash",
    "doteq",
    "leqq",
    "smallfrown",
    "Vdash",
    "Doteq",
    "leqslant",
    "smallsmile",
    "Vvdash",
    "gnapprox",
    "ngeqslant",
    "nsubseteq",
    "precneqq",
    "gneq",
    "ngtr",
    "nsubseteqq",
    "precnsim",
    "gneqq",
    "nleq",
    "nsucc",
    "subsetneq",
    "gnsim",
    "nleqq",
    "nsucceq",
    "subsetneqq",
    "gvertneqq",
    "nleqslant",
    "nsupseteq",
    "succnapprox",
    "lnapprox",
    "nless",
    "nsupseteqq",
    "succneqq",
    "lneq",
    "ntriangleleft",
    "succnsim",
    "lneqq",
    "notin",
    "neg",
    "lnot",
    "ntrianglelefteq",
    "supsetneq",
    "lnsim",
    "notni",
    "ntriangleright",
    "supsetneqq",
    "lvertneqq",
    "ntrianglerighteq",
    "varsubsetneq",
    "ncong",
    "nprec",
    "nvdash",
    "varsubsetneqq",
    "npreceq",
    "nvDash",
    "varsupsetneq",
    "nshortmid",
    "nVDash",
    "varsupsetneqq",
    "ngeq",
    "nshortparallel",
    "nVdash",
    "ngeqq",
    "nsim",
    "precnapprox",
    "circlearrowleft",
    "leftharpoonup",
    "rArr",
    "circlearrowright",
    "leftleftarrows",
    "rarr",
    "curvearrowleft",
    "leftrightarrow",
    "restriction",
    "curvearrowright",
    "Leftrightarrow",
    "rightarrow",
    "Darr",
    "leftrightarrows",
    "Rightarrow",
    "dArr",
    "leftrightharpoons",
    "rightarrowtail",
    "darr",
    "leftrightsquigarrow",
    "rightharpoondown",
    "dashleftarrow",
    "Lleftarrow",
    "rightharpoonup",
    "dashrightarrow",
    "longleftarrow",
    "rightleftarrows",
    "downarrow",
    "Longleftarrow",
    "rightleftharpoons",
    "Downarrow",
    "longleftrightarrow",
    "rightrightarrows",
    "downdownarrows",
    "Longleftrightarrow",
    "rightsquigarrow",
    "downharpoonleft",
    "longmapsto",
    "Rrightarrow",
    "downharpoonright",
    "longrightarrow",
    "Rsh",
    "gets",
    "Longrightarrow",
    "searrow",
    "Harr",
    "looparrowleft",
    "swarrow",
    "hArr",
    "looparrowright",
    "to",
    "harr",
    "Lrarr",
    "twoheadleftarrow",
    "hookleftarrow",
    "lrArr",
    "twoheadrightarrow",
    "hookrightarrow",
    "lrarr",
    "Uarr",
    "iff",
    "Lsh",
    "uArr",
    "impliedby",
    "mapsto",
    "uarr",
    "implies",
    "nearrow",
    "uparrow",
    "Larr",
    "nleftarrow",
    "Uparrow",
    "lArr",
    "nLeftarrow",
    "updownarrow",
    "larr",
    "nleftrightarrow",
    "Updownarrow",
    "leadsto",
    "nLeftrightarrow",
    "upharpoonleft",
    "leftarrow",
    "nrightarrow",
    "upharpoonright",
    "Leftarrow",
    "nRightarrow",
    "upuparrows",
    "leftarrowtail",
    "nwarrow",
    "leftharpoondown",
    "Rarr",
};

pub static FIXED: phf::Map<&'static str, &str> = phf_map! {
    "N" => "ℕ",
    "Z" => "ℤ",
    "Q" => "ℚ",
    "R" => "ℝ",
    "C" => "ℂ",
    "CC" => "ℂ",
    "A" => "𝔸",
    "F" => "𝔽",
    "SS" => "𝕊",
    "natnums" => "ℕ",
    "reals" => "ℝ",
    "Reals" => "ℝ",
    "cnums" => "ℂ",
    "Complex" => "ℂ",
    "Bbbk" => "𝕜",
    "TeX" => "TᴇX",
    "LaTeX" => "LᴬTᴇX",
    "hat" => "̂",
    "tilde" => "̃",
    "bar" => "̄",
    "overline" => "̅",
    "breve" => "̆",
    "widetilde" => "͠",
    "uwidebreve" => "͜",
    "widebreve" => "͝",
    "widepreve" => "͡",
    "uvec" => "͢",
    "degree" => "°",
    "varGamma" => "Γ",
    "varDelta" => "Δ",
    "varTheta" => "Θ",
    "varLambda" => "Λ",
    "varXi" => "Ξ",
    "varPi" => "ϖ",
    "varSigma" => "Σ",
    "varUpsilon" => "Υ",
    "varPhi" => "Φ",
    "varPsi" => "Ψ",
    "varOmega" => "Ω",
    "varepsilon" => "ε",
    "varkappa" => "ϰ",
    "vartheta" => "ϑ",
    "thetasym" => "ϑ",
    "varpi" => "ϖ",
    "varrho" => "ϱ",
    "varsigma" => "ς",
    "varphi" => "φ",
    "digamma" => "ϝ",
    "argmax" => "arg max",
    "argmin" => "arg min",
    "injlim" => "inj lim",
    "liminf" => "lim inf",
    "limsup" => "lim sup",
    "projlim" => "proj lim",
    "cdot" => "⋅",
    "cdotp" => "⋅",
    "dots" => "…",
    "cdots" => "⋯",
    "ldots" => "…",
    "ddots" => "⋱",
    "vdots" => "⋮",
    "prime" => "′",
    "Box" => "□",
    "|" => "∥",
    "lang" => "⟨",
    "rang" => "⟩",
    "vert" => "∣",
    "Vert" => "∥",
    "lVert" => "∥",
    "rVert" => "∥",
    "lceil" => "⌈",
    "rceil" => "⌉",
    "lfloor" => "⌊",
    "rfloor" => "⌋",
    "lmoustache" => "⎰",
    "rmoustache" => "⎱",
    "lgroup" => "⟮",
    "rgroup" => "⟯",
    "ulcorner" => "┌",
    "urcorner" => "┐",
    "llcorner" => "└",
    "lrcorner" => "┘",
    "llbracket" => "[[",
    "rlbracket" => "]]",
    "lBrace" => "{[",
    "rBrace" => "]}",
    "bigotimes" => "⨂",
    "bigvee" => "⋁",
    "bigoplus" => "⨁",
    "bigwedge" => "⋀",
    "bigodot" => "⨀",
    "bigcap" => "⋂",
    "biguplus" => "⨄",
    "bigcup" => "⋃",
    "bigsqcup" => "⨆",
    "wedge" => "∧",
    "curlywedge" => "⋏",
    "barwedge" => "⊼",
    "doublebarwedge" => "⩞",
    "vee" => "∨",
    "curlyvee" => "⋎",
    "veebar" => "⊻",
    "sqcap" => "⊓",
    "sqcup" => "⊔",
    "boxdot" => "⊡",
    "boxplus" => "⊞",
    "boxminus" => "⊟",
    "boxtimes" => "⊠",
    "oplus" => "⊕",
    "ominus" => "⊖",
    "otimes" => "⊗",
    "oslash" => "⊘",
    "uplus" => "⊎",
    "divideontimes" => "⋇",
    "lhd" => "⊲",
    "unlhd" => "⊴",
    "rhd" => "⊳",
    "unrhd" => "⊵",
    "setminus" => "∖",
    "smallsetminus" => "∖",
    "forall" => "∀",
    "complement" => "∁",
    "partial" => "∂",
    "exist" => "∃",
    "exists" => "∃",
    "noexist" => "∄",
    "empty" => "∅",
    "emptyset" => "∅",
    "varnothing" => "⌀",
    "nabla" => "∇",
    "ni" => "∋",
    "blacksquare" => "∎",
    "prod" => "∏",
    "_" => "_",
    "infty" => "∞",
    "textunderscore" => "_",
    "dotsb" => "⋯",
    "infin" => "∞",
    "dotsc" => "…",
    "checkmark" => "✓",
    "textendash" => "–",
    "dotsi" => "⋯",
    "dag" => "†",
    "dotsm" => "⋯",
    "dagger" => "†",
    "textemdash" => "—",
    "dotso" => "…",
    "textdagger" => "†",
    "textasciitilde" => "~",
    "sdot" => "⋅",
    "ddag" => "‡",
    "textasciicircum" => "^",
    "mathellipsis" => "…",
    "ddagger" => "‡",
    "`" => "‘",
    "textellipsis" => "…",
    "textdaggerdbl" => "‡",
    "textquoteleft" => "‘",
    "Dagger" => "‡",
    "lq" => "‘",
    "square" => "□",
    "angle" => "∠",
    "textquoteright" => "’",
    "measuredangle" => "∡",
    "rq" => "′",
    "triangle" => "△",
    "sphericalangle" => "∢",
    "textquotedblleft" => "“",
    "triangledown" => "▽",
    "top" => "⊤",
    "triangleleft" => "◃",
    "bot" => "⊥",
    "textquotedblright" => "”",
    "triangleright" => "▹",
    "$" => "$",
    "colon" => ":",
    "bigtriangledown" => "▽",
    "textdollar" => "$",
    "backprime" => "‵",
    "bigtriangleup" => "△",
    "pounds" => "£",
    "blacktriangle" => "▲",
    "mathsterling" => "£",
    "textless" => "<",
    "blacktriangledown" => "▼",
    "textsterling" => "£",
    "textgreater" => ">",
    "blacktriangleleft" => "◀",
    "yen" => "¥",
    "textbar" => "|",
    "blacktriangleright" => "▶",
    "surd" => "√",
    "textbardbl" => "∥",
    "diamond" => "⋄",
    "textbraceleft" => "{",
    "Diamond" => "◊",
    "textdegree" => "°",
    "textbraceright" => "}",
    "lozenge" => "◊",
    "mho" => "℧",
    "textbackslash" => "\\",
    "blacklozenge" => "⧫",
    "diagdown" => "╲",
    "P" => "¶",
    "star" => "⋆",
    "diagup" => "╱",
    "S" => "§",
    "bigstar" => "★",
    "flat" => "♭",
    "sect" => "§",
    "clubsuit" => "♣",
    "natural" => "♮",
    "copyright" => "©",
    "clubs" => "♣",
    "sharp" => "♯",
    "circledR" => "®",
    "diamondsuit" => "♢",
    "heartsuit" => "♡",
    "textregistered" => "®",
    "diamonds" => "♢",
    "hearts" => "♡",
    "circledS" => "Ⓢ",
    "spadesuit" => "♠",
    "spades" => "♠",
    "maltese" => "✠",
    "minuso" => "∘−",
    "coprod" => "∐",
    "sum" => "∑",
    "plus" => "+",
    "minus" => "−",
    "mp" => "∓",
    "dotplus" => "∔",
    "backslash" => "∖",
    "ast" => "∗",
    "circ" => "∘",
    "bullet" => "∙",
    "mid" => "∣",
    "nmid" => "∤",
    "parallel" => "∥",
    "nparallel" => "∦",
    "land" => "∧",
    "lor" => "∨",
    "cap" => "∩",
    "cup" => "∪",
    "int" => "∫",
    "iint" => "∬",
    "iiint" => "∭",
    "iiiint" => "⨌",
    "oint" => "∮",
    "oiint" => "∯",
    "oiiint" => "∰",
    "intclockwise" => "∱",
    "lcirclerightint" => "∲",
    "rcirclerightint" => "∳",
    "nsimeq" => "≄",
    "congneq" => "≆",
    "eq" => "=",
    "ne" => "≠",
    "neq" => "≠",
    "triangleq" => "≜",
    "doteqdot" => "≑",
    "lessapprox" => "⪅",
    "smile" => "⌣",
    "eqcirc" => "≖",
    "lesseqgtr" => "⋚",
    "sqsubset" => "⊏",
    "eqcolon" => "∹",
    "minuscolon" => "∹",
    "lesseqqgtr" => "⪋",
    "sqsubseteq" => "⊑",
    "Eqcolon" => "−∷",
    "minuscoloncolon" => "-∷",
    "lessgtr" => "≶",
    "sqsupset" => "⊐",
    "approx" => "≈",
    "eqqcolon" => "≕",
    "equalscolon" => "≕",
    "lesssim" => "≲",
    "sqsupseteq" => "⊒",
    "approxcolon" => "≈:",
    "Eqqcolon" => "=∷",
    "equalscoloncolon" => "=∷",
    "ll" => "≪",
    "Subset" => "⋐",
    "approxcoloncolon" => "≈∷",
    "eqsim" => "≂",
    "lll" => "⋘",
    "subset" => "⊂",
    "sub" => "⊂",
    "approxeq" => "≊",
    "eqslantgtr" => "⪖",
    "llless" => "⋘",
    "subseteq" => "⊆",
    "sube" => "⊆",
    "asymp" => "≍",
    "eqslantless" => "⪕",
    "lt" => "<",
    "subseteqq" => "⫅",
    "backepsilon" => "∍",
    "equiv" => "≡",
    "succ" => "≻",
    "backsim" => "∽",
    "fallingdotseq" => "≒",
    "models" => "⊨",
    "succapprox" => "⪸",
    "backsimeq" => "⋍",
    "frown" => "⌢",
    "multimap" => "⊸",
    "succcurlyeq" => "≽",
    "between" => "≬",
    "ge" => "≥",
    "origof" => "⊶",
    "succeq" => "⪰",
    "bowtie" => "⋈",
    "geq" => "≥",
    "owns" => "∋",
    "succsim" => "≿",
    "bumpeq" => "≏",
    "geqq" => "≧",
    "Supset" => "⋑",
    "Bumpeq" => "≎",
    "geqslant" => "⩾",
    "perp" => "⊥",
    "supset" => "⊃",
    "gg" => "≫",
    "pitchfork" => "⋔",
    "supseteq" => "⊇",
    "supe" => "⊇",
    "colonapprox" => ":≈",
    "ggg" => "⋙",
    "prec" => "≺",
    "supseteqq" => "⫆",
    "Colonapprox" => "∷≈",
    "coloncolonapprox" => "∷≈",
    "gggtr" => "⋙",
    "precapprox" => "⪷",
    "thickapprox" => "≈",
    "coloneq" => ":−",
    "colonminus" => ":-",
    "gt" => ">",
    "preccurlyeq" => "≼",
    "thicksim" => "∼",
    "Coloneq" => "∷−",
    "coloncolonminus" => "∷−",
    "gtrapprox" => "⪆",
    "preceq" => "⪯",
    "trianglelefteq" => "⊴",
    "coloneqq" => "≔",
    "colonequals" => "≔",
    "gtreqless" => "⋛",
    "precsim" => "≾",
    "Coloneqq" => "∷=",
    "coloncolonequals" => "∷=",
    "gtreqqless" => "⪌",
    "propto" => "∝",
    "trianglerighteq" => "⊵",
    "colonsim" => ":∼",
    "gtrless" => "≷",
    "risingdotseq" => "≓",
    "varpropto" => "∝",
    "Colonsim" => "∷∼",
    "coloncolonsim" => "∷∼",
    "gtrsim" => "≳",
    "shortmid" => "∣",
    "vartriangle" => "△",
    "cong" => "≅",
    "imageof" => "⊷",
    "shortparallel" => "∥",
    "vartriangleleft" => "⊲",
    "curlyeqprec" => "⋞",
    "in" => "∈",
    "isin" => "∈",
    "sim" => "∼",
    "vartriangleright" => "⊳",
    "curlyeqsucc" => "⋟",
    "Join" => "⋈",
    "simcolon" => "∼:",
    "vcentcolon" => ":",
    "ratio" => ":",
    "dashv" => "⊣",
    "le" => "≤",
    "simcoloncolon" => "∼∷",
    "vdash" => "⊢",
    "dblcolon" => "∷",
    "coloncolon" => "∷",
    "leq" => "≤",
    "simeq" => "≃",
    "vDash" => "⊨",
    "doteq" => "≐",
    "leqq" => "≦",
    "smallfrown" => "⌢",
    "Vdash" => "⊩",
    "Doteq" => "≑",
    "leqslant" => "⩽",
    "smallsmile" => "⌣",
    "Vvdash" => "⊪",
    "gnapprox" => "⪊",
    "ngeqslant" => "≱",
    "nsubseteq" => "⊈",
    "precneqq" => "⪵",
    "gneq" => "⪈",
    "ngtr" => "≯",
    "nsubseteqq" => "⊈",
    "precnsim" => "⋨",
    "gneqq" => "≩",
    "nleq" => "≰",
    "nsucc" => "⊁",
    "subsetneq" => "⊊",
    "gnsim" => "⋧",
    "nleqq" => "≰",
    "nsucceq" => "⋡",
    "subsetneqq" => "⫋",
    "gvertneqq" => "≩",
    "nleqslant" => "≰",
    "nsupseteq" => "⊉",
    "succnapprox" => "⪺",
    "lnapprox" => "⪉",
    "nless" => "≮",
    "nsupseteqq" => "⊉",
    "succneqq" => "⪶",
    "lneq" => "⪇",
    "ntriangleleft" => "⋪",
    "succnsim" => "⋩",
    "lneqq" => "≨",
    "notin" => "∉",
    "neg" => "¬",
    "lnot" => "¬",
    "ntrianglelefteq" => "⋬",
    "supsetneq" => "⊋",
    "lnsim" => "⋦",
    "notni" => "∌",
    "ntriangleright" => "⋫",
    "supsetneqq" => "⫌",
    "lvertneqq" => "≨",
    "ntrianglerighteq" => "⋭",
    "varsubsetneq" => "⊊",
    "ncong" => "≆",
    "nprec" => "⊀",
    "nvdash" => "⊬",
    "varsubsetneqq" => "⫋",
    "npreceq" => "⋠",
    "nvDash" => "⊭",
    "varsupsetneq" => "⊋",
    "nshortmid" => "∤",
    "nVDash" => "⊯",
    "varsupsetneqq" => "⫌",
    "ngeq" => "≱",
    "nshortparallel" => "∦",
    "nVdash" => "⊮",
    "ngeqq" => "≱",
    "nsim" => "≁",
    "precnapprox" => "⪹",
    "circlearrowleft" => "↺",
    "leftharpoonup" => "↼",
    "rArr" => "⇒",
    "circlearrowright" => "↻",
    "leftleftarrows" => "⇇",
    "rarr" => "→",
    "curvearrowleft" => "↶",
    "leftrightarrow" => "↔",
    "restriction" => "↾",
    "curvearrowright" => "↷",
    "Leftrightarrow" => "⇔",
    "rightarrow" => "→",
    "Darr" => "⇓",
    "leftrightarrows" => "⇆",
    "Rightarrow" => "⇒",
    "dArr" => "⇓",
    "leftrightharpoons" => "⇋",
    "rightarrowtail" => "↣",
    "darr" => "↓",
    "leftrightsquigarrow" => "↭",
    "rightharpoondown" => "⇁",
    "dashleftarrow" => "⇠",
    "Lleftarrow" => "⇚",
    "rightharpoonup" => "⇀",
    "dashrightarrow" => "⇢",
    "longleftarrow" => "⟵",
    "rightleftarrows" => "⇄",
    "downarrow" => "↓",
    "Longleftarrow" => "⟸",
    "rightleftharpoons" => "⇌",
    "Downarrow" => "⇓",
    "longleftrightarrow" => "⟷",
    "rightrightarrows" => "⇉",
    "downdownarrows" => "⇊",
    "Longleftrightarrow" => "⟺",
    "rightsquigarrow" => "⇝",
    "downharpoonleft" => "⇃",
    "longmapsto" => "⟼",
    "Rrightarrow" => "⇛",
    "downharpoonright" => "⇂",
    "longrightarrow" => "⟶",
    "Rsh" => "↱",
    "gets" => "←",
    "Longrightarrow" => "⟹",
    "searrow" => "↘",
    "Harr" => "⇔",
    "looparrowleft" => "↫",
    "swarrow" => "↙",
    "hArr" => "⇔",
    "looparrowright" => "↬",
    "to" => "→",
    "harr" => "↔",
    "Lrarr" => "⇔",
    "twoheadleftarrow" => "↞",
    "hookleftarrow" => "↩",
    "lrArr" => "⇔",
    "twoheadrightarrow" => "↠",
    "hookrightarrow" => "↪",
    "lrarr" => "↔",
    "Uarr" => "⇑",
    "iff" => "⟺",
    "Lsh" => "↰",
    "uArr" => "⇑",
    "impliedby" => "⟸",
    "mapsto" => "↦",
    "uarr" => "↑",
    "implies" => "⟹",
    "nearrow" => "↗",
    "uparrow" => "↑",
    "Larr" => "⇐",
    "nleftarrow" => "↚",
    "Uparrow" => "⇑",
    "lArr" => "⇐",
    "nLeftarrow" => "⇍",
    "updownarrow" => "↕",
    "larr" => "←",
    "nleftrightarrow" => "↮",
    "Updownarrow" => "⇕",
    "leadsto" => "⇝",
    "nLeftrightarrow" => "⇎",
    "upharpoonleft" => "↿",
    "leftarrow" => "←",
    "nrightarrow" => "↛",
    "upharpoonright" => "↾",
    "Leftarrow" => "⇐",
    "nRightarrow" => "⇏",
    "upuparrows" => "⇈",
    "leftarrowtail" => "↢",
    "nwarrow" => "↖",
    "leftharpoondown" => "↽",
    "Rarr" => "⇒",
    "pm" => "±",
    "plusmn" => "±",
    "times" => "×",
    "ltimes" => "⋉",
    "rtimes" => "⋊",
    "div" => "÷",
    "aleph" => "ℵ",
    "alef" => "ℵ",
    "alefsym" => "ℵ",
    "beth" => "ℶ",
    "gimel" => "ℷ",
    "daleth" => "ℸ",
    "eth" => "ð",
    "ell" => "ℓ",
    "wp" => "℘",
    "weierp" => "℘",
    "," => " ",
    ">" => " ",
    ":" => " ",
    ";" => "  ",
    "!" => "",
    "quad" => "    ",
    "qquad" => "      ",
    "thinspace" => " ",
    "medspace" => " ",
    "thickspace" => "  ",
    "enspace" => "  ",
    "negthickspace" => "",
    "negthinspace" => "",
    "negmedspace" => "",
    "(" => "(",
    ")" => ")",
    "[" => "[",
    "]" => "]",
    "{" => "{",
    "}" => "}",
    "%" => "%",
    "\\" => "\n",
    "newline" => "\n",
    "Game" => "⅁",
    "because" => "∵",
    "suchthat" => "∴",
    "proposition" => "𝐏𝐫𝐨𝐩𝐨𝐬𝐢𝐭𝐢𝐨𝐧",
    "lemma" => "𝐋𝐞𝐦𝐦𝐚",
    "theorem" => "𝐓𝐡𝐞𝐨𝐫𝐞𝐦",
    "corollary" => "𝐂𝐨𝐫𝐨𝐥𝐥𝐚𝐫𝐲",
    "definition" => "𝐃𝐞𝐟𝐢𝐧𝐢𝐭𝐢𝐨𝐧",
    "remark" => "𝐑𝐞𝐦𝐚𝐫𝐤",
    "hypothesis" => "𝐇𝐲𝐩𝐨𝐭𝐡𝐞𝐬𝐢𝐬",
    "conjecture" => "𝐂𝐨𝐧𝐣𝐞𝐜𝐭𝐮𝐫𝐞",
    "axiom" => "𝐀𝐱𝐢𝐨𝐦",
    "example" => "𝐄𝐱𝐚𝐦𝐩𝐥𝐞",
    "proof" => "𝑝𝑟𝑜𝑜𝑓",
    "KaTeX" => "KᴬTᴇX",
    "UniTeX" => "UⁿᵢTᴇX",
    "Agda" => "𝐴gda",
    "Lean" => "L∃∀N",
    "sumtop" => "⎲",
    "sumbottom" => "⎳",
    "lbraceuend" => "⎧",
    "lbracemid" => "⎨",
    "lbracelend" => "⎩",
    "arcsin" => "arcsin",
    "arccos" => "arccos",
    "arctan" => "arctan",
    "arctg" => "arctg",
    "arcctg" => "arcctg",
    "arg" => "arg",
    "ch" => "ch",
    "cos" => "cos",
    "det" => "det",
    "gcd" => "gcd",
    "inf" => "inf",
    "cosec" => "cosec",
    "cosh" => "cosh",
    "cot" => "cot",
    "cotg" => "cotg",
    "coth" => "coth",
    "csc" => "csc",
    "ctg" => "ctg",
    "cth" => "cth",
    "lim" => "lim",
    "max" => "max",
    "deg" => "deg",
    "dim" => "dim",
    "exp" => "exp",
    "hom" => "hom",
    "ker" => "ker",
    "lg" => "lg",
    "ln" => "ln",
    "log" => "log",
    "min" => "min",
    "plim" => "plim",
    "Pr" => "Pr",
    "sup" => "sup",
    "sec" => "sec",
    "sin" => "sin",
    "sinh" => "sinh",
    "sh" => "sh",
    "tan" => "tan",
    "tanh" => "tanh",
    "tg" => "tg",
    "th" => "th",
    "Alpha" => "Α",
    "Beta" => "Β",
    "Gamma" => "Γ",
    "Delta" => "Δ",
    "Epsilon" => "Ε",
    "Zeta" => "Ζ",
    "Eta" => "Η",
    "Theta" => "Θ",
    "Iota" => "Ι",
    "Kappa" => "Κ",
    "Lambda" => "Λ",
    "Mu" => "Μ",
    "Nu" => "Ν",
    "Xi" => "Ξ",
    "Omicron" => "Ο",
    "Pi" => "Π",
    "Rho" => "Ρ",
    "Sigma" => "Σ",
    "Tau" => "Τ",
    "Upsilon" => "Υ",
    "Phi" => "Φ",
    "Chi" => "Χ",
    "Psi" => "Ψ",
    "Omega" => "Ω",
    "alpha" => "α",
    "beta" => "β",
    "gamma" => "γ",
    "delta" => "δ",
    "epsilon" => "ϵ",
    "zeta" => "ζ",
    "eta" => "η",
    "theta" => "θ",
    "iota" => "ι",
    "kappa" => "κ",
    "lambda" => "λ",
    "mu" => "μ",
    "nu" => "ν",
    "xi" => "ξ",
    "omicron" => "ο",
    "pi" => "π",
    "rho" => "ρ",
    "sigma" => "σ",
    "tau" => "τ",
    "upsilon" => "υ",
    "phi" => "φ",
    "chi" => "χ",
    "psi" => "ψ",
    "omega" => "ω",
    "dollar" => "$",
};
